# Generated by Django 2.1.5 on 2019-01-04 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('descricao', models.TextField()),
                ('horario', models.TextField()),
                ('idade_minima', models.IntegerField()),
                ('ponto_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponto_turistico_atracao', to='core.PontosTuristicos')),
            ],
        ),
    ]
